/** Declaration file generated by dts-gen */

export = XmlStream;

declare class XmlStream {
    constructor(stream: any, encoding: any);

    collect(selector: any): void;

    on(eventName: any, listener: any): void;

    pause(): void;

    preserve(selector: any, whitespace: any): void;

    resume(): void;
}
